### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by pwqw** [bayo/gamepad2midi#1]
I did
``` bash
$ sudo apt-get install librtmidi-dev
$ sudo pip install python-rtmidi
# edit mygamepad2midi.py
$ ./mygamepad2midi.py
```
exceptions.. and more exceptions.. finally:
```bash
No MIDI ports found.
Traceback (most recent call last):
  File "./mygamepad2midi.py", line 16, in <module>
    main()
  File "./mygamepad2midi.py", line 13, in main
    gamepad2midi("JACK", mapping)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 220, in gamepad2midi
    job = Gamepad2Midi(api, mapping)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 99, in __init__
    self.midi_connector = midi_connector_factory(api)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 81, in midi_connector_factory
    return RtmidiMidiConnector(rtmidi_api)
  File "/tmp/gamepad2midi/util/RtmidiMidiConnector.py", line 17, in __init__
    raise Exception("No port was found")
Exception: No port was found
```
How to install it?

(ubuntu 16.04)

**Comment by bayo** [comment]
Did you fix your problem?
Did you install JACK? ALSA should be more portable.

**Comment by pwqw** [comment]
Yes, I have JACK installed with ALSA. And running.

Look, the first run throw this:
``` bash
Traceback (most recent call last):
  File "mygamepad2midi.py", line 16, in <module>
    main()
  File "mygamepad2midi.py", line 13, in main
    gamepad2midi("JACK", mapping)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 222, in gamepad2midi
    job = Gamepad2Midi(api, mapping)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 101, in __init__
    self.midi_connector = midi_connector_factory(api)
  File "/tmp/gamepad2midi/gamepad2midi.py", line 78, in midi_connector_factory
    "WS_KS": rtmidi.API_WINDOWS_KS,
AttributeError: 'module' object has no attribute 'API_WINDOWS_KS'
```
So I deleted the lines [77](https://github.com/bayo/gamepad2midi/blob/master/gamepad2midi.py#L77) and [78](https://github.com/bayo/gamepad2midi/blob/master/gamepad2midi.py#L78).

Then when rerun throw the first comment output.

**Comment by bayo** [comment]
I mean, did you try to use `gamepad2midi("ALSA", mapping)`. I guess my JACK connector is just not working at all. But JACK allow you to reach the ALSA midi ports, as i remember.

I will try to take some time to clean up this project. That's an old stuff :-)

**Comment by bayo** [comment]
That's funny, I found 3 rtmidi projects on pypi (`python-rtmidi`, `rtmidi-python`, and `rtmidi`), but i guess your problem with `API_WINDOWS_KS` is more something relative to librtmidi itself (http://trac.chrisarndt.de/code/changeset/1359/projects).

**Comment by pwqw** [comment]
aaaaaaaw yes! `gamepad2midi("ALSA", mapping)` works, thanks!!
I will create a pull request with the instructions.

:rofl: and what rtmidi projects do you think that is using?

**Comment by bayo** [comment]
It was using an older version, but i have no idea which one it was.

All i know is the one you use is the only one i am able to install today (`python-rtmidi`). I have to check all that things.

**Comment by pwqw** [comment]
For now its all ok :+1:
